theme = "tokyonight"

[editor]
bufferline = "multiple"
cursorcolumn = true
# Minimum severity to show a diagnostic after the end of a line
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "error" # Show inline diagnostics when the cursor is on the line
other-lines = "disable" # Don't expand diagnostics unless the cursor is on the line

[editor.file-picker]
hidden = false
